### ISSUE TITLE
PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by themak1985** [greenleafadvancement/org.civicrm.googlegroups#14]
We are upgrading a site to PHP 8.1 and were getting a ton of errors due to some extensions. We could not figure out why this one was not working, but after installing the master - not the latest release - i would no longer get any errors on the extension page.

However - then I found a new issue:

When going to any contact group settings or when going to the extension settings - I am met with a fatal error:

```
[08-Jan-2024 18:05:41 America/New_York] PHP Warning:  Undefined array key "state" in /home/tarabnyc/www/www/wp-content/uploads/civicrm/templates_c/en_US/%%E9/E96/E966E9A3%%Sync.tpl.php on line 7
[08-Jan-2024 18:05:41 America/New_York] PHP Warning:  Undefined array key "location" in /home/tarabnyc/www/www/wp-content/uploads/civicrm/templates_c/en_US/%%ED/ED7/ED78F5CC%%formButtons.tpl.php on line 44
[08-Jan-2024 18:05:45 America/New_York] PHP Fatal error:  Uncaught Error: Undefined constant GuzzleHttp\ClientInterface::MAJOR_VERSION in /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/vendor/guzzlehttp/guzzle/src/Utils.php:116
Stack trace:
#0 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/vendor/guzzlehttp/guzzle/src/functions.php(71): GuzzleHttp\Utils::defaultUserAgent()
#1 /home/tarabnyc/www/www/wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/vendor/guzzlehttp/guzzle/src/Client.php(194): GuzzleHttp\default_user_agent()
#2 /home/tarabnyc/www/www/wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/vendor/guzzlehttp/guzzle/src/Client.php(75): GuzzleHttp\Client->configureDefaults(Array)
#3 /home/tarabnyc/www/www/wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/vendor/google/apiclient/src/Google/Client.php(1113): GuzzleHttp\Client->__construct(Array)
#4 /home/tarabnyc/www/www/wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/vendor/google/apiclient/src/Google/Client.php(1075): Google_Client->createDefaultHttpClient()
#5 /home/tarabnyc/www/www/wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/vendor/google/apiclient/src/Google/Client.php(281): Google_Client->getHttpClient()
#6 /home/tarabnyc/www/www/wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/CRM/Googlegroups/Form/Settings.php(49): Google_Client->fetchAccessTokenWithRefreshToken('1//0dNXvVKQB1oR...')
#7 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(740): CRM_Googlegroups_Form_Settings->buildQuickForm()
#8 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Display.php(76): CRM_Core_Form->buildForm()
#9 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Display->perform(Object(CRM_Googlegroups_Form_Settings), 'display')
#10 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Googlegroups_Form_Settings), 'display')
#11 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(355): HTML_QuickForm_Page->handle('display')
#12 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/CRM/Utils/Wrapper.php(98): CRM_Core_Controller->run()
#13 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(295): CRM_Utils_Wrapper->run('CRM_Googlegroup...', 'Settings', Array)
#14 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem(Array)
#15 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke(Array)
#16 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm.php(1231): CRM_Core_Invoke::invoke(Array)
#17 /home/tarabnyc/www/www/wp-includes/class-wp-hook.php(324): CiviCRM_For_WordPress->invoke('')
#18 /home/tarabnyc/www/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#19 /home/tarabnyc/www/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#20 /home/tarabnyc/www/www/wp-admin/admin.php(259): do_action('toplevel_page_C...')
#21 {main}
  thrown in /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/vendor/guzzlehttp/guzzle/src/Utils.php on line 116
```
Downgrading to php 7.4 did not fix this issue.
I uninstalled the extension - deleted the custom groups - deleted scheduled jobs - reinstalled the master - still no good.
Repeated, this time deleted googlegroups_settings - now I get a fresh start - screen loads - I enter credentials - click authorize - get asked which google account to choose - make selection - boom fatal error - same errors.

```
[08-Jan-2024 18:38:26 America/New_York] PHP Fatal error:  Uncaught Error: Undefined constant GuzzleHttp\ClientInterface::MAJOR_VERSION in /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/vendor/guzzlehttp/guzzle/src/Utils.php:116
Stack trace:
#0 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/vendor/guzzlehttp/guzzle/src/functions.php(71): GuzzleHttp\Utils::defaultUserAgent()
#1 /home/tarabnyc/www/www/wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/vendor/guzzlehttp/guzzle/src/Client.php(194): GuzzleHttp\default_user_agent()
#2 /home/tarabnyc/www/www/wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/vendor/guzzlehttp/guzzle/src/Client.php(75): GuzzleHttp\Client->configureDefaults(Array)
#3 /home/tarabnyc/www/www/wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/vendor/google/apiclient/src/Google/Client.php(1113): GuzzleHttp\Client->__construct(Array)
#4 /home/tarabnyc/www/www/wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/vendor/google/apiclient/src/Google/Client.php(1075): Google_Client->createDefaultHttpClient()
#5 /home/tarabnyc/www/www/wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/vendor/google/apiclient/src/Google/Client.php(194): Google_Client->getHttpClient()
#6 /home/tarabnyc/www/www/wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/CRM/Googlegroups/Form/Settings.php(18): Google_Client->fetchAccessTokenWithAuthCode('4/0AfJohXlehodH...')
#7 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(719): CRM_Googlegroups_Form_Settings->preProcess()
#8 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Display.php(76): CRM_Core_Form->buildForm()
#9 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Display->perform(Object(CRM_Googlegroups_Form_Settings), 'display')
#10 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Googlegroups_Form_Settings), 'display')
#11 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(355): HTML_QuickForm_Page->handle('display')
#12 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/CRM/Utils/Wrapper.php(98): CRM_Core_Controller->run()
#13 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(295): CRM_Utils_Wrapper->run('CRM_Googlegroup...', 'Settings', Array)
#14 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem(Array)
#15 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke(Array)
#16 /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm.php(1231): CRM_Core_Invoke::invoke(Array)
#17 /home/tarabnyc/www/www/wp-includes/class-wp-hook.php(324): CiviCRM_For_WordPress->invoke('')
#18 /home/tarabnyc/www/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#19 /home/tarabnyc/www/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#20 /home/tarabnyc/www/www/wp-admin/admin.php(259): do_action('toplevel_page_C...')
#21 {main}
  thrown in /home/tarabnyc/www/www/wp-content/plugins/civicrm/civicrm/vendor/guzzlehttp/guzzle/src/Utils.php on line 116
```
Tried again with php 7.4 - still no dice. If I keep the extension active - i can't edit contact group settings either.

For now the extension is disabled - I have no clue the issue anymore.

**Comment by deepak-srivastava** [comment]
@themak1985 Please try the latest release v2.4, and re-open if you still see any issues.

**Comment by themak1985** [comment]
Just wanted to say thank you - this works great.

**Comment by guyiac** [comment]
@themak1985 - thank you for the feedback and we are glad it's working as expected.
